apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx_app
    type: front-end
  name: nginx-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx_app
  template:
    metadata:
      labels:
        app: nginx_app
    spec:
      containers:
      - image: nginx:latest
        name: nginx-container